### ISSUE TITLE
What kind of network do you used ?

### ISSUE THREAD

**Issue by xianlubird** [swarmzilla/swarm3k#44]
Does all the containers use build-in overlay network driver on swarm mode ?

**Comment by chanwit** [comment]
Yes. It's the built-in one we were using.

**Comment by BSWANG** [comment]
In our stress scene, we meet this [problem](https://github.com/docker/libnetwork/issues/1522) use the build-in overlay network. one overlay network can not create more than 1024 containers by default due to default linux ARP entry limits. how to solve this problem in the swarm3k project? @chanwit

**Comment by alexanderkjeldaas** [comment]
@BSWANG could this be the tuning done in point `#10` in `README.md`?
