### ISSUE TITLE
10 Nodes contributions for Swarm3k

### ISSUE THREAD

**Issue by ajeetraina** [swarmzilla/swarm3k#6]
Hi Chanwit, add 10 nodes contribution from my end for this effort. Hope we have strong monitoring tool this time.

**Comment by ajeetraina** [comment]
Twitter handler - @ajeetsraina
Company - Dell Inc.

**Comment by chanwit** [comment]
Thank you Ajeet !!
Could you be able to open a PR and adding yourself to the README.md?

If not, please let me know if you'd like me to add one for you.

**Comment by chanwit** [comment]
Merged your contribution. I'm closing this one. Thank you :-)

**Comment by ajeetraina** [comment]
Thank You.
